# Generated by Django 6.1.1 on 2026-10-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='category',
            field=models.CharField(choices=[('NEBULOUS', 'Nebulous'), ('STAR', 'Star'), ('GALAXY', 'Galaxy'), ('PLANET', 'Planet')], default='None', max_length=100),
        ),
    ]
